base: &base
  adapter: postgresql
  encoding: utf8
  username:
  password:
  host: 127.0.0.1
  pool: 5

development:
  <<: *base
  database: ios_alchemy_development

test:
  <<: *base
  database: ios_alchemy_test

staging:
  <<: *base
  database: ios_alchemy_staging

production:
  <<: *base
  database: ios_alchemy_production